replicaCount: 1
image:
  repository: blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: "0.11.0-d2c3cdc"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext:
  fsGroup: 2000
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
service:
  type: ClusterIP
  port: 80
#- Enables using a PVC to store frigate database, otherwise it will use ephermeral storage on node that doesn't persist on pod restart
storage:
  enabled: true
  size: 10Gi
  storageClass: default
#- Controls mounting various hardware devices into the container for hardware acceleration
hwaccel:
  enabled: false
  intel: false
  nvidia: false
  usb: false
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frigate.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
mqtt:
  enabled: true
  #- If you have an existing broker provide the hostname, this is required if mqtt.enabled is false
  externalBrokerHostname: ~