replicaCount: 1
image:
  repository: blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: "0.11.0-d2c3cdc"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext:
  privileged: true
service:
  type: ClusterIP
  port: 80
storage:
  enabled: true
  size: 10Gi
  storageClass: ~
hwaccel:
  intelEnabled: false
  usbEnabled: false
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frigate.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
secrets: []
cameras: {}
mqtt:
  enabled: true
  externalBrokerHostname: ~
