apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmct.fullname" . }}
  labels:
    {{- include "openmct.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openmct.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openmct.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openmct.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.plugins.enabled }}
       - name: plugins
        persistentVolumeClaim:
          claimName: {{ .values.plugins.claimName }}
      {{- end }}
      {{- if .Values.loader.enabled }}
       - name: loader
        persistentVolumeClaim:
          claimName: {{ .values.loader.claimName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.loader.enabled }}
            - name: OPENMCT_PLUGIN_LOADER_SCRIPT
              value: {{ .Values.loader.loaderName }}
          {{- end }}
          volumeMounts:
          {{- if .Values.plugins.enabled }}
            - mountPath: "/usr/src/app/public/plugins"
              name: plugins
          {{- end }}
          {{- if .Values.loader.enabled }}
            - mountPath: "/usr/src/app/loaders"
              name: loader
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
