replicaCount: 1
image:
  repository: ghcr.io/bryopsida/syslog-portal
  pullPolicy: Always
  tag: "main"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9091"
podSecurityContext:
  fsGroup: 1000
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 514
resources:
  limits:
    cpu: 256m
    memory: 128Mi
  requests:
    cpu: 256m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
logLevel: "info"
archiver:
  # -- Toggle archiving the data to a remote system, if disabled stdout is the destination
  enabled: false
  # -- Toggle usage of auth in the archiver
  authEnabled: false
  # -- Set the type of archiver, can be MONGO or POUCHDB
  type: "MONGO"
  # -- Controls the interval between syncs to the remote dabase when using the POUCHDB archiver
  syncInterval: 300000
  # -- The location of the local database store when using the POUCHDB archiver
  databaseFolder: /opt/syslog-portal/data
  # -- Hostname of the remote destination targetted by the archiver
  hostname: ~
  # -- Destination port targetted by the archiver
  port: 27017
  # -- Username for the remote destination of the archiver
  username: ~
  # -- Password for the remote destination of the archiver
  password: ~
  # -- Path to a username file
  usernameFile: ~
  # -- Path to a password file
  passwordFile: ~
  # -- Name of an existing secret
  existingSecret: ~
  # -- List of keys, in order of priority, that will be used for partition keys if applicable
  partitionKeyPriorityList:
    - app
    - hostname
    - severity
  