image:
  repository: ghcr.io/koush/scrypted
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
hostNetwork: true
securityContext:
  readOnlyRootFilesystem: true
  runAsUser: 2000
  runAsGroup: 2000
  capabilities:
    drop:
     - 'All'
    add:
    - 'setuid'
    - 'setgid'
    - 'chown'
    - 'DAC_OVERRIDE'

storage:
  size: 10Gi
  className: ~

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: scrypted.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
