{{- if and .Values.archiver.enabled (not .Values.archiver.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "syslog-portal.defaultArchiverSecretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.archiver.password | b64enc }}
  username: {{ .Values.archiver.username | b64enc }}
{{- end }}