apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  production.json: |
    {
      "server": {
        "archiver": {
          "type": "{{ default "MONGO" .Values.archiver.type }}",
          "hostname": "{{ .Values.archiver.hostname }}",
          "port": {{ default 27017 .Values.archiver.port }},
          "syncInterval": {{ .Values.archiver.syncInterval }},
          "databaseFolder": "{{ .Values.archiver.databaseFolder }}",
          "partitionKeyPriorityList": {{ .Values.archiver.partitionKeyPriorityList | toJson }}
        }
      }
    }
