apiVersion: v1
kind: Service
metadata:
  name: {{ include "syslog-portal.fullname" . }}
  labels:
    {{- include "syslog-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: syslog
      protocol: UDP
      name: syslog
  selector:
    {{- include "syslog-portal.selectorLabels" . | nindent 4 }}
