apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-claim-token
  namespace: {{ .Release.Namespace }}
data:
  claim-token: {{ required "You must provide a value for .claimToken" .Values.claimToken | b64enc }}
