apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: plex
      protocol: TCP
      name: plex
    {{- if .Values.overseerr.enabled }}
    - port: {{ .Values.overseerr.port }}
      targetPort: overseerr
      protocol: TCP
      name: overseerr
    {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
