# Default values for openmct.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/bryopsida/openmct
  pullPolicy: Always
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: openmct.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1024m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
plugins:
  useInline: true
  usePvc: false
  pluginPvcName: openmct-plugins
  inline:
    plugin-ct.js: |
      function PluginConfidenceTest () {
        console.log('Greatings from PluginConfidenceTest defined in a configmap')
      }
loader:
  useInline: true
  usePvc: false
  loaderPvcName: openmct-loader
  loaderName: loader.js
  inline: |
    console.log('Hello world from loader-ct.js, provided by a configmap')
    PluginConfidenceTest()
