{{- range  $k, $v := .Values.managedStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $k }}
  namespace: {{ $.Release.Namespace }}
spec:
{{- if $v.storageClassName }}
  storageClassName: {{ $v.storageClassName }}
{{- end }}
  accessModes:
  {{- if $.Values.manyPods }}
    - ReadWriteMany
  {{- else }}
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ $v.size }}
{{- end }}
