---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app.fullname" . }}
  labels:
    {{- include "node-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "node-app.selectorLabels" . | nindent 4 }}
{{- if .Values.devSideCar.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app.fullname" . }}-ssh
  labels:
    {{- include "node-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.devSideCar.service.type }}
  ports:
    - port: {{ .Values.devSideCar.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "node-app.selectorLabels" . | nindent 4 }}
{{- end }}
