name: Release Charts
on:
  push: 
    branches: 
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Add Repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add k8s-at-home https://k8s-at-home.com/charts/
          helm repo update
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          charts_dir: charts